name = "Calcutron33"
uuid = "1fd0e58f-89f5-4e25-960f-202a58a6edf0"
authors = ["Erik Engheim <erik.engheim@mac.com>"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
julia = "1"
